spring.application.name=springboot-ecommerce
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.security.user.name=admin
spring.security.user.password=$2a$10$u9DWnRyg.uvb3kLHqMIhoOdj894xbBzwDuSHb1G4W0CHQfdMRJRce
jwt.secret=+il5ItsHZbSy7C9AI6yfz0DviMGz+pxJlIyXoQzOiPg=
jwt.expiration=3600000